var Constants = {
    HONEYCOMB: 0,
    SQUARE: 1,
    SliceViewWidth: '500px',
    SliceViewHeight: '500px',
    Renderer: 'two',
    RendererTwo: 'two',
    RendererThree: 'three',
    RendererKinetic: 'kinetic',
    helixLayer: 'helixLayer',
    defaultLayer: 'defaultLayer',
    zlow: 0,
    zmid: 1,
    zhigh: 2,
    zhighest: 3,
    ScaffoldStrand: 'Scaffold',
    Scaffold: 0,
    Staple: 1,
};

var cadnanoEvents = {
    documentPartAddedSignal: 'documentPartAddedSignal',
    partVirtualHelixAddedSignal: 'partVirtualHelixAddedSignal',
    partActiveSliceResizedSignal: 'partActiveSliceResizedSignal',
    partHelicesInitializedSignal: 'partHelicesInitializedSignal',
    partRemovedSignal: 'partRemovedSignal',
    documentClearSelectionsSignal: 'documentClearSelectionsSignal',
    partVirtualHelixRemovedSignal: 'partVirtualHelixRemovedSignal',
    strandSetStrandAddedSignal: 'strandSetStrandAddedSignal',
    partStepSizeChangedSignal: 'partStepSizeChangedSignal',
    updatePreXoverItemsSignal: 'updatePreXoverItemsSignal',
    partStrandChangedSignal: 'partStrandChangedSignal',
    strandSetStrandRemovedSignal: 'strandSetStrandRemovedSignal',
    strandUpdateSignal: 'strandUpdateSignal',
    updateSkipInsertItemsSignal: 'updateSkipInsertItemsSignal',
    moveSliceItemToFirstSignal: 'moveSliceItemToFirstSignal',
    moveSliceItemToLastSignal: 'moveSliceItemToLastSignal',
};


/* Slice View Colours */
var colours = {
    white: '#ffffff',
    black: '#000000',
    red: '#ff0000',
    darkred: '#aa0000',
    bluefill: '#99ccff',
    bluestroke: '#0066cc',
    bluishstroke: '',
    orangefill: '#ffcc99',
    orangestroke: '#cc6633',
    lightorangefill: '#ffeab7',
    lightorangestroke: '#ea8451',
    grayfill: '#eeeeee',
    graystroke: '#666666',
    lightgraystroke: '#dddddd',
    lightergraystroke: '#b0b0b0',
    strokewidth: 1,
    hoverstrokewidth: 3,
};
